version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-server
    image: jenkins:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: football-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  jenkins_home:
  postgres_data: